### ISSUE TITLE
Problemas con id's

### ISSUE THREAD

**Issue by jd-apprentice** [nicoprten/NP-S-TODO-LIST#1]
Creando varias tareas con el mismo nombre al parecer le vas asignando un numero, viendo que pasando el 10 puede pasar que toque una id 1 y 11, cuando selecciono la tarea de abajo de todo selecciona la opuesta, imagino que por que toma como referencia el primer 1 que encuentra

![Repeat-id](https://user-images.githubusercontent.com/68082746/169726186-e1fe4fda-94ed-4ec3-a01e-0844389f5570.gif)

**Comment by nicoprten** [comment]
Solucionado el problema de los IDs utilizando el siguiente código:
![image](https://user-images.githubusercontent.com/41525219/169738376-a083ffb1-abc9-4e91-8fc4-9ebbcb42750b.png)
No es la forma más optima pero para casos como estos proyectos funciona muy bien.

También saqué el filtro de que solo se puedan agregar tareas con 3 caracteres o más y si se agrega una misma tarea te aparece un mensaje diciendo "La tarea ya está agregada".
![image](https://user-images.githubusercontent.com/41525219/169739042-83ee7b1c-e60f-4496-9634-f72f0b9c4371.png)

**Comment by jd-apprentice** [comment]
Buenos improvements!, ahora si va perfecto 😄
